### ISSUE TITLE
Users layout

### ISSUE THREAD

**Issue by LiyinZ** [x-factory/neat-client#5]
## Todo
- [ ] add user custom dialog
- [ ] delete all disabled users
- [ ] disable toaster
- [ ] search box
- [ ] search filter function
- [ ] popup detail window for update
- [ ] popup window for adding

**Comment by LiyinZ** [comment]
## Done
- [x] BIG round add button
- [x] link to disabled users
- [x] fixed height scroll
- [x] add confirmation for reset
- [x] add confirmation for delete
- [x] delete toaster
- [x] disabled users
- [x] link to enabled users
